# Generated by Django 4.1.2 on 2022-12-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=50)),
                ('password', models.CharField(default='admin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platenumber', models.CharField(default=True, max_length=50)),
                ('date_in', models.DateField(default=True, max_length=50)),
                ('time_in', models.TimeField(default=True, max_length=50)),
                ('date_out', models.DateField(max_length=50, null=True)),
                ('time_out', models.TimeField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=500)),
                ('courseyr', models.CharField(max_length=25)),
                ('Ownerfname', models.CharField(max_length=50)),
                ('Ownermname', models.CharField(max_length=50)),
                ('Ownerlname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mobnum', models.CharField(max_length=50)),
                ('landline', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=50)),
                ('platenumber', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('prevStickerNo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
